version: '3'

services:
  exosuite-api-php-fpm:
    environment:
      - INSTALL_PATH=${API_FOLDER_NAME} # TODO: move to prod
    build:
      context: ./php-fpm/${ENVIRONMENT}
    restart: ${RESTART_MODE}
    container_name: exosuite-api-php-fpm
    volumes:
      - ${API_FOLDER_PATH}:/${API_FOLDER_NAME}
    networks:
    - exosuite-network

  nginx:
    hostname: api.exosuite.local exosuite.local
    restart: ${RESTART_MODE}
    image: nginx:latest
    environment:
      - WEBSITE_ROOT_PATH=/${WEBSITE_FOLDER_NAME}/public
      - API_ROOT_PATH=/${API_FOLDER_NAME}/public
    extra_hosts:
      - "web.exosuite.local:127.0.0.1"
      - "api.exosuite.local:127.0.0.1"
    ports:
      - "80:80"
    volumes:
      - ./server_confs/exosuite.${ENVIRONMENT}.conf:/etc/nginx/conf.d/website.conf.template
      - ./server_confs/api.exosuite.${ENVIRONMENT}.conf:/etc/nginx/conf.d/api.conf.template
      - ${API_FOLDER_PATH}:/${API_FOLDER_NAME}
    container_name: nginx
    networks:
      - exosuite-network


  resolver:
    image: dvdarias/docker-hoster:latest
    volumes:
      - /etc/hosts:/tmp/hosts
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - exosuite-network
    container_name: resolver


#  database:
#    restart: ${RESTART_MODE}
#    image: postgres:11-alpine


networks:
  exosuite-network:
    driver: bridge