version: '3'

services:
  exosuite-api-php-fpm:
    working_dir: ${STORAGE_PATH}/${API_FOLDER_NAME}
    build:
      context: ./php-fpm
    restart: ${RESTART_MODE}
    container_name: exosuite-api-php-fpm-${BUILD_NUMBER}
    volumes:
      - ${API_FOLDER_PATH}:${STORAGE_PATH}/${API_FOLDER_NAME}
    networks:
      - exosuite-network

  nginx:
    hostname: api.exosuite.${BUILD_NUMBER}.local
    restart: ${RESTART_MODE}
    build:
      context: ./server_confs/${ENVIRONMENT}/api
      args:
        - CONFIG_FILE=api.exosuite.conf
        - FPM_SERVER=exosuite-api-php-fpm-${BUILD_NUMBER}
        - ROOT_PATH=${STORAGE_PATH}/${API_FOLDER_NAME}
        - SERVER_NAME=api.exosuite.${BUILD_NUMBER}.local
        - DB_HOST=exosuite-users-api-postgres-${BUILD_NUMBER}
    container_name: nginx-api-${BUILD_NUMBER}
    depends_on:
      - exosuite-api-php-fpm
      - exosuite-users-api-postgres
    volumes:
      - ${API_FOLDER_PATH}:${STORAGE_PATH}/${API_FOLDER_NAME}
    networks:
      - exosuite-network

  exosuite-users-api-postgres:
    restart: ${RESTART_MODE}
    image: postgres:11-alpine
    container_name: exosuite-users-api-postgres-${BUILD_NUMBER}
    environment:
      - POSTGRES_DB=exosuite-users-api
      - POSTGRES_USER=exosuite
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - exosuite-network


networks:
  exosuite-network:
    driver: bridge