version: '3'

services:
  exosuite-api-php-fpm:
    environment:
      - INSTALL_PATH=/exosuite-users-api
    build:
      context: ./php-fpm
    restart: ${RESTART_MODE}
    volumes:
      - ./exosuite-users-api:/exosuite-users-api
    container_name: exosuite-api-php-fpm

  nginx:
    restart: ${RESTART_MODE}
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./server_confs/exosuite.${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf
      - ./server_confs/exosuite.${ENVIRONMENT}.api.conf:/etc/nginx/conf.d/api.conf
      - ./exosuite-users-api:/exosuite-users-api
    container_name: nginx


