version: '3'

services:
  exosuite-api-php-fpm:
    working_dir: ${STORAGE_PATH}/${API_FOLDER_NAME}
    build:
      context: ./php-fpm
    restart: ${RESTART_MODE}
    container_name: exosuite-api-php-fpm
    volumes:
      - ${API_FOLDER_PATH}:${STORAGE_PATH}/${API_FOLDER_NAME}
      - /etc/hosts:/etc/hosts
    networks:
      - exosuite-network

  exosuite-website-php-fpm:
    working_dir: ${STORAGE_PATH}/${WEBSITE_FOLDER_NAME}
    build:
      context: ./php-fpm
    restart: ${RESTART_MODE}
    container_name: exosuite-website-php-fpm
    volumes:
      - ${WEBSITE_FOLDER_PATH}:${STORAGE_PATH}/${WEBSITE_FOLDER_NAME}
      - /etc/hosts:/etc/hosts
    networks:
      - exosuite-network

  nginx-website:
    hostname: exosuite.local
    restart: ${RESTART_MODE}
    build:
      context: ./server_confs/${ENVIRONMENT}
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ${WEBSITE_FOLDER_PATH}:${STORAGE_PATH}/${WEBSITE_FOLDER_NAME}
    container_name: nginx-website
    depends_on:
      - exosuite-website-php-fpm
      - exosuite-website-postgres
    networks:
      - exosuite-network

  exosuite-nginx:
    hostname: exosuite.local api.exosuite.local
    restart: ${RESTART_MODE}
    ports:
      - ${NGINX_PORT}
    build:
      context: ./server_confs/${ENVIRONMENT}/reverse
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: exosuite-nginx
    depends_on:
      - nginx-users-api
      - nginx-website
    networks:
      - exosuite-network

  nginx-users-api:
    hostname: api.exosuite.local
    restart: ${RESTART_MODE}
    build:
      context: ./server_confs/${ENVIRONMENT}
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ${API_FOLDER_PATH}:${STORAGE_PATH}/${API_FOLDER_NAME}
    container_name: nginx-users-api
    depends_on:
      - exosuite-api-php-fpm
      - exosuite-api-postgres
    networks:
      - exosuite-network

  resolver:
    image: dvdarias/docker-hoster:latest
    volumes:
      - /etc/hosts:/tmp/hosts
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - exosuite-network
    container_name: resolver

  exosuite-api-postgres:
    restart: ${RESTART_MODE}
    build:
      context: ./postgres-postgis
    ports:
      - ${API_POSTGRES_PORT}
    container_name: exosuite-api-postgres
    environment:
      - POSTGRES_DB=exosuite-users-api
      - POSTGRES_USER=exosuite
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - exosuite-network
    volumes:
      - ${STORAGE_PATH}/exosuite-api-postgres:/var/lib/postgresql/data/pgdata

  exosuite-website-postgres:
    restart: ${RESTART_MODE}
    image: postgres:11-alpine
    container_name: exosuite-website-postgres
    environment:
      - POSTGRES_DB=exosuite-website
      - POSTGRES_USER=exosuite
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - exosuite-network
    volumes:
      - ${STORAGE_PATH}/exosuite-website-postgres:/var/lib/postgresql/data/pgdata

  exosuite-laravel-echo-server:
    restart: ${RESTART_MODE}
    build:
      context: ./laravel-echo-server
    container_name: exosuite-laravel-echo-server
    environment:
      - APP_URL=http://nginx-users-api
      - APP_DEBUG=true
      - REDIS_HOST=${REDIS_HOST}
      - LES_DB=redis
    networks:
      - exosuite-network
    ports:
      - "6001:6001"
    depends_on:
      - exosuite-redis-live

  exosuite-redis-store:
    restart: ${RESTART_MODE}
    container_name: exosuite-redis-store
    image: redis:alpine
    volumes:
      - ${STORAGE_PATH}/exosuite-redis-store:/data
    networks:
      - exosuite-network
    command: ["sh", "-c",'docker-entrypoint.sh --appendonly yes']
    ports:
      - "6379:6379"

  exosuite-redis-live:
    restart: ${RESTART_MODE}
    container_name: exosuite-redis-live
    image: redis:alpine
    volumes:
      - ${STORAGE_PATH}/exosuite-redis-live:/data
    networks:
      - exosuite-network
    command: ["sh", "-c",'docker-entrypoint.sh --appendonly yes']

  exosuite-laravel-horizon:
    restart: ${RESTART_MODE}
    container_name: exosuite-laravel-horizon
    build:
      context: laravel-artisan
    volumes:
      - ${API_FOLDER_PATH}:${STORAGE_PATH}/${API_FOLDER_NAME}
    environment:
      - COMMAND=horizon
      - WORKDIR=${STORAGE_PATH}/${API_FOLDER_NAME}
    networks:
      - exosuite-network
    depends_on:
      - exosuite-laravel-echo-server

  exosuite-scheduler:
    restart: ${RESTART_MODE}
    container_name: exosuite-scheduler
    build:
      context: laravel-artisan
    volumes:
      - ${API_FOLDER_PATH}:${STORAGE_PATH}/${API_FOLDER_NAME}
    environment:
      - COMMAND=schedule:daemon
      - WORKDIR=${STORAGE_PATH}/${API_FOLDER_NAME}
    networks:
      - exosuite-network
    depends_on:
      - exosuite-laravel-echo-server


networks:
  exosuite-network:
    driver: bridge