version: '3'

services:

  exosuite-api-php-fpm:
    working_dir: ${STORAGE_PATH}/${API_FOLDER_NAME}
    build:
      context: ./php-fpm
    restart: ${RESTART_MODE}
    container_name: exosuite-api-php-fpm-${BUILD_NUMBER}
    volumes:
      - ${API_FOLDER_PATH}:${STORAGE_PATH}/${API_FOLDER_NAME}
    networks:
      - exosuite-network

  exosuite-users-api-postgres:
    image: mdillon/postgis:11-alpine
    container_name: exosuite-users-api-postgres-${BUILD_NUMBER}
    environment:
      - POSTGRES_DB=exosuite-users-api
      - POSTGRES_USER=exosuite
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - exosuite-network

  exosuite-elasticsearch:
    container_name: exosuite-elasticsearch-${BUILD_NUMBER}
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "discovery.type=single-node"
    networks:
      - exosuite-network

networks:
  exosuite-network:
    driver: bridge