version: '3'

services:
  exosuite-website-php-fpm:
    working_dir: ${STORAGE_PATH}/${WEBSITE_FOLDER_NAME}
    build:
      context: ./php-fpm
    restart: ${RESTART_MODE}
    container_name: exosuite-website-php-fpm-${BUILD_NUMBER}
    volumes:
      - ${WEBSITE_FOLDER_PATH}:${STORAGE_PATH}/${WEBSITE_FOLDER_NAME}
    networks:
      - zalenium_exosuite-tests

  nginx-website:
    hostname: "exosuite.${BUILD_NUMBER}.local app.exosuite.${BUILD_NUMBER}.local"
    restart: ${RESTART_MODE}
    build:
      context: ./server_confs/${ENVIRONMENT}/website
      args:
        - CONFIG_FILE=exosuite.conf
        - FPM_SERVER=exosuite-website-php-fpm-${BUILD_NUMBER}
        - ROOT_PATH=${STORAGE_PATH}/${WEBSITE_FOLDER_NAME}
        - SERVER_NAME=exosuite.${BUILD_NUMBER}.local
        - APP_NAME=app.exosuite.${BUILD_NUMBER}.local
        - DB_HOST=exosuite-website-postgres-${BUILD_NUMBER}
    container_name: nginx-website-${BUILD_NUMBER}
    depends_on:
      - exosuite-website-php-fpm
      - exosuite-website-postgres
    volumes:
      - ${WEBSITE_FOLDER_PATH}:${STORAGE_PATH}/${WEBSITE_FOLDER_NAME}
    networks:
      - zalenium_exosuite-tests

  exosuite-website-postgres:
    restart: ${RESTART_MODE}
    image: postgres:11.1-alpine
    container_name: exosuite-website-postgres-${BUILD_NUMBER}
    environment:
      - POSTGRES_DB=exosuite-website
      - POSTGRES_USER=exosuite
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - zalenium_exosuite-tests

networks:
  zalenium_exosuite-tests:
    external: true