version: '3'

services:

  exosuite-users-api-postgres:
    build:
      context: ./postgres-postgis
    container_name: exosuite-users-api-postgres-${BUILD_NUMBER}
    environment:
      - POSTGRES_DB=exosuite-users-api
      - POSTGRES_USER=exosuite
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - exosuite-network

  exosuite-elasticsearch:
    container_name: exosuite-elasticsearch-${BUILD_NUMBER}
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "discovery.type=single-node"
    networks:
      - exosuite-network

networks:
  exosuite-network:
    driver: bridge