version: '3'

services:
  exosuite-users-api-postgres:
    restart: always
    image: postgres:11-alpine
    ports:
      - 5432
    container_name: exosuite-users-api-postgres
    environment:
      - POSTGRES_DB=exosuite-users-api
      - POSTGRES_USER=exosuite
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/exosuite-users-api-postgres:/var/lib/postgresql/data/pgdata